name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ['current']
        racket-variant: ['CS']
    name: Build & Test on Racket ${{ matrix.racket-version }} (${{ matrix.racket-variant }})
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: x64
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: raco pkg install --batch --auto http-easy-lib/ http-easy-test/ http-easy/
      - run: raco test http-easy-test/
