name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '7.7', '7.8', '7.9', 'current' ]
    name: Build & Test on Racket ${{ matrix.racket-version }}
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.13
        with:
          architecture: x64
          variant: 'CS'
          version: ${{ matrix.racket-version }}
      - run: raco pkg install --batch --auto http-easy/ http-easy-test/
      - run: raco test http-easy-test/
