name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: x64
          variant: 'CS'
          version: '7.7'
      - run: raco pkg install --batch --auto http-easy/ http-easy-test/
      - run: raco test http-easy-test/
